name: MedicoRAG
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py311hee9e2a2_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-doc=0.0.3=pyhcf101f3_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anthropic=0.72.0=pyhd8ed1ab_0
  - anyio=4.11.0=pyhcf101f3_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.0=hed7f23c_16
  - aws-c-cal=0.9.2=hd08b81e_1
  - aws-c-common=0.12.4=h6caf38d_0
  - aws-c-compression=0.3.1=habbe1e8_6
  - aws-c-event-stream=0.5.5=ha7b4b11_1
  - aws-c-http=0.10.2=hf8ac5b2_3
  - aws-c-io=0.21.0=hc6344be_1
  - aws-c-mqtt=0.13.1=h8af1df2_4
  - aws-c-s3=0.8.3=hf857400_1
  - aws-c-sdkutils=0.2.4=habbe1e8_1
  - aws-checksums=0.2.7=habbe1e8_2
  - aws-crt-cpp=0.32.10=hcb36028_3
  - aws-sdk-cpp=1.11.510=h29a0155_14
  - azure-core-cpp=1.14.0=hd50102c_0
  - azure-identity-cpp=1.10.0=hc602bab_0
  - azure-storage-blobs-cpp=12.13.0=h7585a09_1
  - azure-storage-common-cpp=12.8.0=h9ca1f76_1
  - azure-storage-files-datalake-cpp=12.12.0=hcdd55da_1
  - blas=1.0=openblas
  - brotli-python=1.1.0=py311hf719da1_4
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.4=hca03da5_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py311h3a79f62_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - cpython=3.11.14=py311hd8ed1ab_2
  - datasets=2.14.4=pyhd8ed1ab_0
  - dill=0.3.7=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - dnspython=2.8.0=pyhcf101f3_0
  - docstring_parser=0.17.0=pyhd8ed1ab_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - faiss=1.9.0=py311hc0156c1_0_cpu
  - faiss-cpu=1.9.0=hd610c6a_0
  - fastapi=0.121.0=h67827d6_0
  - fastapi-cli=0.0.13=pyhcf101f3_0
  - fastapi-core=0.121.0=pyhcf101f3_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - frozenlist=1.7.0=py311h8740443_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gflags=2.2.2=hf9b8971_1005
  - glog=0.7.1=heb240a5_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py311hb9fe3ed_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hf-xet=1.2.0=py310h6ce4931_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py311h9408147_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jiter=0.11.1=py311h0f0954d_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libarrow=20.0.0=h7b33710_9_cpu
  - libarrow-acero=20.0.0=hcfcb59a_9_cpu
  - libarrow-dataset=20.0.0=hcfcb59a_9_cpu
  - libarrow-substrait=20.0.0=hb375905_9_cpu
  - libblas=3.9.0=17_osxarm64_openblas
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=17_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=21.1.5=hf598326_0
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libfaiss=1.9.0=h682f5e0_0_cpu
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libgoogle-cloud=2.36.0=h8564cf0_2
  - libgoogle-cloud-storage=2.36.0=h7081f7f_2
  - libgrpc=1.73.1=h3063b79_1
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.9.0=17_osxarm64_openblas
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.23=openmp_hc731615_0
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libparquet=20.0.0=hff5ddb4_9_cpu
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=6.31.1=h658db43_2
  - libre2-11=2025.11.05=h91c62da_0
  - libsqlite=3.51.0=h9a5124b_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.21.0=h64651cc_0
  - libtiff=4.7.0=hfce79cd_1
  - libtorch=2.8.0=cpu_generic_h0fc8bc6_2
  - libutf8proc=2.10.0=h74a6958_0
  - libuv=1.51.0=h6caf38d_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.5=h376fa9f_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.5=h4a912ad_0
  - lz4-c=1.10.0=h286801f_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311ha9b3269_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.6.3=py311h30e7462_0
  - multiprocess=0.70.15=py311heffc1b2_1
  - ncurses=6.5=hee39554_0
  - networkx=3.4.2=pyh267e887_2
  - nlohmann_json=3.12.0=h248ca61_1
  - nomkl=1.0=h5ca1d4c_0
  - numpy=1.26.4=py311h7125741_0
  - openjpeg=2.5.3=h889cd5d_1
  - openssl=3.5.4=h5503f6c_0
  - optree=0.17.0=py311h5a5e7c7_2
  - orc=2.1.2=h1fd2763_1
  - orjson=3.10.14=py311h2aea54e_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hdb8e4fa_1
  - pillow=11.3.0=py311h1f9957d_3
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - pooch=1.8.2=pyhd8ed1ab_3
  - prometheus-cpp=1.3.0=h0967b3e_0
  - propcache=0.3.1=py311h4921393_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pyarrow=20.0.0=py311ha1ab1f8_0
  - pyarrow-core=20.0.0=py311he04fa90_0_cpu
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.4=pyh3cfb1c2_0
  - pydantic-core=2.41.5=py311h71babbd_0
  - pydantic-settings=2.11.0=pyh3cfb1c2_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.0=h3ba56d0_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-gil=3.11.14=hd8ed1ab_2
  - python-multipart=0.0.20=pyhff2d567_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py311hacbd903_1
  - python_abi=3.11=8_cp311
  - pytorch=2.8.0=cpu_generic_py311_hf0c13c8_2
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311ha9b3269_0
  - re2=2025.11.05=h64b956e_0
  - readline=8.3=h0b18652_0
  - regex=2025.11.3=py311h9408147_1
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.2.0=pyhcf101f3_0
  - rich-toolkit=0.15.1=pyhcf101f3_0
  - safetensors=0.6.2=py311hc638b3f_1
  - scikit-learn=1.7.2=py311h0f965f6_0
  - scipy=1.10.1=py311h0bcca16_0
  - sentence-transformers=5.1.2=pyhd8ed1ab_0
  - setuptools=75.8.2=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - snappy=1.2.2=hd121638_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sqlite=3.51.0=hab6afd1_0
  - starlette=0.49.2=pyhfdc7a7d_0
  - sympy=1.14.0=pyh2585a3b_105
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hcd8a7d5_0
  - tokenizers=0.22.1=py311h4175fc0_0
  - tqdm=4.67.1=py311hb6e6a13_0
  - transformers=4.57.1=pyhd8ed1ab_0
  - typer=0.20.0=pyhdb1f59b_0
  - typer-slim=0.20.0=pyhcf101f3_0
  - typer-slim-standard=0.20.0=h65a100f_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - uvicorn=0.38.0=pyh31011fe_0
  - uvicorn-standard=0.38.0=h31011fe_0
  - uvloop=0.22.1=py311h9408147_1
  - watchfiles=1.1.1=py311h0f0954d_0
  - websockets=15.0.1=py311hb76fab6_2
  - wheel=0.45.1=py311hca03da5_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xxhash=0.8.3=haa4e116_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.22.0=py311ha9b3269_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - zstandard=0.25.0=py311h5bb9006_1
  - zstd=1.5.7=h6491c7d_2
prefix: /opt/anaconda3/envs/MedicoRAG
